"""create initial persistence schema

Revision ID: 2de522f37af0
Revises:
Create Date: 2026-07-14 10:32:34.763426

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2de522f37af0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_projects_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_projects_type_created_at', ['project_type', 'created_at'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index('ix_activity_events_project_created_at', ['project_id', 'created_at'], unique=False)

    op.create_table('script_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_no', name='uq_script_versions_project_version')
    )
    with op.batch_alter_table('script_versions', schema=None) as batch_op:
        batch_op.create_index('ix_script_versions_project_id', ['project_id'], unique=False)

    op.create_table('script_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_version_id', sa.String(length=36), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('estimated_duration', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_version_id', 'segment_index', name='uq_script_segments_version_index')
    )
    with op.batch_alter_table('script_segments', schema=None) as batch_op:
        batch_op.create_index('ix_script_segments_version_id', ['script_version_id'], unique=False)

    op.create_table('storyboard_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('script_version_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('total_estimated_duration', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_no', name='uq_storyboard_versions_project_version')
    )
    with op.batch_alter_table('storyboard_versions', schema=None) as batch_op:
        batch_op.create_index('ix_storyboard_versions_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_storyboard_versions_script_version_id', ['script_version_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('script_version_id', sa.String(length=36), nullable=True),
    sa.Column('storyboard_version_id', sa.String(length=36), nullable=True),
    sa.Column('parent_job_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('external_job_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storyboard_version_id'], ['storyboard_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_job_id', name='uq_generation_jobs_provider_external')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_generation_jobs_parent_job_id', ['parent_job_id'], unique=False)
        batch_op.create_index('ix_generation_jobs_project_status', ['project_id', 'status'], unique=False)

    op.create_table('storyboard_scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storyboard_version_id', sa.String(length=36), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('media_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('estimated_duration', sa.Float(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_version_id'], ['storyboard_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyboard_version_id', 'scene_index', name='uq_storyboard_scenes_version_index')
    )
    with op.batch_alter_table('storyboard_scenes', schema=None) as batch_op:
        batch_op.create_index('ix_storyboard_scenes_version_id', ['storyboard_version_id'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('storyboard_scene_id', sa.String(length=36), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('remote_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storyboard_scene_id'], ['storyboard_scenes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'role', 'local_path', name='uq_assets_job_role_path')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('ix_assets_job_id', ['job_id'], unique=False)
        batch_op.create_index('ix_assets_local_path', ['local_path'], unique=False)
        batch_op.create_index('ix_assets_project_type', ['project_id', 'asset_type'], unique=False)
        batch_op.create_index('ix_assets_storyboard_scene_id', ['storyboard_scene_id'], unique=False)

    op.create_table('workflow_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('workflow_json', sa.JSON(), nullable=False),
    sa.Column('ui_json', sa.JSON(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_snapshots_job_id', ['job_id'], unique=False)

    op.create_table('output_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('generation_job_id', sa.String(length=36), nullable=True),
    sa.Column('storyboard_version_id', sa.String(length=36), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('video_asset_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_job_id'], ['generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storyboard_version_id'], ['storyboard_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_no', name='uq_output_versions_project_version')
    )
    with op.batch_alter_table('output_versions', schema=None) as batch_op:
        batch_op.create_index('ix_output_versions_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_output_versions_project_id')

    op.drop_table('output_versions')
    with op.batch_alter_table('workflow_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_workflow_snapshots_job_id')

    op.drop_table('workflow_snapshots')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('ix_assets_storyboard_scene_id')
        batch_op.drop_index('ix_assets_project_type')
        batch_op.drop_index('ix_assets_local_path')
        batch_op.drop_index('ix_assets_job_id')

    op.drop_table('assets')
    with op.batch_alter_table('storyboard_scenes', schema=None) as batch_op:
        batch_op.drop_index('ix_storyboard_scenes_version_id')

    op.drop_table('storyboard_scenes')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_jobs_project_status')
        batch_op.drop_index('ix_generation_jobs_parent_job_id')

    op.drop_table('generation_jobs')
    with op.batch_alter_table('storyboard_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_storyboard_versions_script_version_id')
        batch_op.drop_index('ix_storyboard_versions_project_id')

    op.drop_table('storyboard_versions')
    with op.batch_alter_table('script_segments', schema=None) as batch_op:
        batch_op.drop_index('ix_script_segments_version_id')

    op.drop_table('script_segments')
    with op.batch_alter_table('script_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_script_versions_project_id')

    op.drop_table('script_versions')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_events_project_created_at')

    op.drop_table('activity_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_type_created_at')
        batch_op.drop_index('ix_projects_status_created_at')
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
