"""Create and execute exact, repository-contained audit cleanup manifests."""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWED_DIRECTORY_ROOTS = (
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "build",
    "dist",
    "frontend/dist",
    "frontend/test-results",
    "frontend/playwright-report",
    "audit/full-agent-test/logs/build-artifacts",
)
PYTHON_CACHE_PARENTS = (
    "api",
    "military_video_gen",
    "tests",
    "scripts",
    "migrations",
)
EXPLICIT_FILES = (
    "frontend/tsconfig.tsbuildinfo",
    "frontend/tsconfig.app.tsbuildinfo",
    "frontend/tsconfig.node.tsbuildinfo",
)


def _relative(path: Path) -> str:
    return path.resolve().relative_to(REPO_ROOT).as_posix()


def _is_allowed(relative_path: str) -> bool:
    path = Path(relative_path)
    if path.is_absolute() or ".." in path.parts:
        return False
    normalized = path.as_posix()
    if normalized in EXPLICIT_FILES:
        return True
    if any(
        normalized == root or normalized.startswith(f"{root}/")
        for root in ALLOWED_DIRECTORY_ROOTS
    ):
        return True
    return any(
        normalized.startswith(f"{parent}/")
        and ("/__pycache__/" in f"/{normalized}/" or normalized.endswith(".pyc"))
        for parent in PYTHON_CACHE_PARENTS
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _tracked_files() -> set[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
    )
    return {
        item.decode("utf-8", errors="surrogateescape")
        for item in result.stdout.split(b"\0")
        if item
    }


def _category(relative_path: str) -> tuple[str, str, str]:
    if "__pycache__" in relative_path or relative_path.endswith(".pyc"):
        return (
            "python-bytecode",
            "Python bytecode cache generated by imports/tests",
            "rerun Python or pytest",
        )
    if relative_path.startswith((".pytest_cache/", ".ruff_cache/", ".mypy_cache/")):
        return (
            "tool-cache",
            "local test/lint cache",
            "rerun the corresponding test or lint command",
        )
    if relative_path.endswith(".tsbuildinfo"):
        return (
            "typescript-cache",
            "TypeScript incremental compiler cache",
            "run npm run typecheck",
        )
    if relative_path.startswith("frontend/test-results/") or relative_path.startswith(
        "frontend/playwright-report/"
    ):
        return (
            "browser-test-output",
            "Playwright output generated by the audit",
            "run npm run e2e",
        )
    if relative_path.startswith("frontend/dist/"):
        return (
            "frontend-build-output",
            "Vite build output generated by the audit",
            "run npm run build",
        )
    return (
        "package-build-output",
        "package/build artifact generated by the audit",
        "run uv build or the corresponding build command",
    )


def discover_candidates() -> list[Path]:
    candidates: set[Path] = set()
    for relative_root in ALLOWED_DIRECTORY_ROOTS:
        root = REPO_ROOT / relative_root
        if root.is_file():
            candidates.add(root)
        elif root.is_dir():
            candidates.update(path for path in root.rglob("*") if path.is_file())
    for relative_parent in PYTHON_CACHE_PARENTS:
        parent = REPO_ROOT / relative_parent
        if not parent.is_dir():
            continue
        for cache_dir in parent.rglob("__pycache__"):
            candidates.update(path for path in cache_dir.rglob("*") if path.is_file())
        candidates.update(path for path in parent.rglob("*.pyc") if path.is_file())
    for relative_file in EXPLICIT_FILES:
        path = REPO_ROOT / relative_file
        if path.is_file():
            candidates.add(path)
    return sorted(candidates, key=_relative)


def create_manifest(manifest_path: Path, pass_name: str) -> None:
    tracked = _tracked_files()
    records = []
    for path in discover_candidates():
        relative_path = _relative(path)
        if not _is_allowed(relative_path):
            raise RuntimeError(f"candidate escaped allowlist: {relative_path}")
        category, reason, recovery = _category(relative_path)
        is_tracked = relative_path in tracked
        records.append(
            {
                "pass": pass_name,
                "path": relative_path,
                "size_bytes": path.stat().st_size,
                "sha256": _sha256(path),
                "git_tracked": is_tracked,
                "classification": "KEEP" if is_tracked else "DELETE_AFTER_TEST",
                "deletion_reason": reason,
                "reference_check_result": (
                    "tracked file: deletion forbidden"
                    if is_tracked
                    else "path is confined to an explicit regenerable cache/build root"
                ),
                "regenerable": not is_tracked,
                "risk": "low" if not is_tracked else "high",
                "recovery_method": recovery,
                "category": category,
                "deleted": False,
            }
        )

    payload = {
        "generated_at": datetime.now(timezone.utc).astimezone().isoformat(),
        "repository_root": "<WORKTREE>",
        "policy": {
            "exact_file_records": True,
            "hash_verified_before_delete": True,
            "tracked_files_deleted": False,
            "protected_roots": [
                ".git/**",
                ".env",
                ".playwright-cli/**",
                "output/**",
                "data/**",
                "temp/**",
                "assets/**",
            ],
        },
        "passes": [],
        "records": [],
    }
    if manifest_path.exists():
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    payload["passes"].append(
        {
            "name": pass_name,
            "record_count": len(records),
            "total_bytes": sum(record["size_bytes"] for record in records),
        }
    )
    payload["records"].extend(records)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def execute_manifest(manifest_path: Path, pass_name: str) -> None:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    deleted_files = 0
    deleted_bytes = 0
    for record in payload["records"]:
        if record["pass"] != pass_name or record["deleted"]:
            continue
        relative_path = record["path"]
        if not _is_allowed(relative_path):
            raise RuntimeError(f"manifest path escaped allowlist: {relative_path}")
        if record["git_tracked"]:
            record["deletion_error"] = "tracked file protected"
            continue
        path = (REPO_ROOT / relative_path).resolve()
        path.relative_to(REPO_ROOT)
        if not path.is_file():
            record["deletion_error"] = "file disappeared before cleanup"
            continue
        if _sha256(path) != record["sha256"]:
            record["deletion_error"] = "hash changed after manifest creation"
            continue
        path.unlink()
        record["deleted"] = True
        deleted_files += 1
        deleted_bytes += record["size_bytes"]

    allowed_directories: list[Path] = []
    for relative_root in (*ALLOWED_DIRECTORY_ROOTS, *PYTHON_CACHE_PARENTS):
        root = REPO_ROOT / relative_root
        if root.is_dir():
            allowed_directories.extend(
                sorted(
                    (path for path in root.rglob("*") if path.is_dir()),
                    key=lambda item: len(item.parts),
                    reverse=True,
                )
            )
    for directory in allowed_directories:
        try:
            directory.rmdir()
        except OSError:
            pass
    for relative_root in ALLOWED_DIRECTORY_ROOTS:
        root = REPO_ROOT / relative_root
        if root.is_dir():
            try:
                root.rmdir()
            except OSError:
                pass

    for pass_record in payload["passes"]:
        if pass_record["name"] == pass_name:
            pass_record["deleted_files"] = deleted_files
            pass_record["deleted_bytes"] = deleted_bytes
            pass_record["completed_at"] = datetime.now(timezone.utc).astimezone().isoformat()
    manifest_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def write_git_lists(base: str, changed_path: Path, deleted_path: Path) -> None:
    def names(*args: str) -> set[str]:
        output = subprocess.run(
            ["git", *args, "-z"],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
        ).stdout
        return {
            Path(entry.decode("utf-8", errors="surrogateescape")).as_posix()
            for entry in output.split(b"\0")
            if entry
        }

    paths = names("diff", "--name-only", base)
    paths.update(names("ls-files", "--others", "--exclude-standard"))
    paths = {
        path
        for path in paths
        if path != ".playwright-cli" and not path.startswith(".playwright-cli/")
    }
    deleted = names("diff", "--diff-filter=D", "--name-only", base)

    changed_path.write_text("\n".join(sorted(paths)) + "\n", encoding="utf-8")
    deleted_path.write_text("\n".join(sorted(deleted)) + ("\n" if deleted else ""), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    manifest_parser = subparsers.add_parser("manifest")
    manifest_parser.add_argument("manifest_path", type=Path)
    manifest_parser.add_argument("pass_name")

    delete_parser = subparsers.add_parser("delete")
    delete_parser.add_argument("manifest_path", type=Path)
    delete_parser.add_argument("pass_name")

    lists_parser = subparsers.add_parser("git-lists")
    lists_parser.add_argument("base")
    lists_parser.add_argument("changed_path", type=Path)
    lists_parser.add_argument("deleted_path", type=Path)

    args = parser.parse_args()
    if args.command == "manifest":
        create_manifest(args.manifest_path.resolve(), args.pass_name)
    elif args.command == "delete":
        execute_manifest(args.manifest_path.resolve(), args.pass_name)
    else:
        write_git_lists(
            args.base,
            args.changed_path.resolve(),
            args.deleted_path.resolve(),
        )


if __name__ == "__main__":
    main()
